# Generated by Django 4.2.6 on 2023-10-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='emails',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='passwords',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='usernames',
            new_name='username',
        ),
    ]
