# Generated by Django 4.2.3 on 2023-08-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_firstname_school_lastname_school_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
