# Generated by Django 4.2.6 on 2023-10-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_emails_school_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
