# Generated by Django 4.2.6 on 2023-10-11 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_school_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='last_login',
        ),
    ]
