# Generated by Django 4.2.6 on 2023-10-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_school_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
