# Generated by Django 4.2.4 on 2023-08-08 16:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_myusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
    ]
